apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ .Values.applicationSet.name }}
  namespace: {{ .Values.applicationSet.namespace }}
spec:
  generators:
    - list:
        elements:
          {{- range .Values.applicationSet.generators }}
          - namespace: {{ .namespace }}
            appname: "app-{{ .namespace }}"  # Adding appname parameter
          {{- end }}
  template:
    metadata:
      name: '{{`{{appname}}`}}'  # Using appname instead of namespace for the name
    spec:
      project: {{ .Values.applicationSet.project }}
      source:
        repoURL: {{ .Values.applicationSet.template.repoUrl }}
        path: {{ .Values.applicationSet.template.path }}
        targetRevision: {{ .Values.applicationSet.template.targetRevision }}
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{`{{namespace}}`}}'
      syncPolicy:
        automated: {}